### PR TITLE
refactor/All Run rustfmt & included a rustfmt.toml for consistency.

### PR DESCRIPTION
**Pull request by dirvine**
This is again (sorry) another trivial PR. Simply rustfmt. 

I have taken a few days to look at NEAT a bit closer and wonder if there are a few things we need to consider (innovation numbers, connect genes and node genes). I am mostly still understanding the Stanly paper though. Be good to have a place to compare notes here somehow. Not sure hot to do this, perhaps through issues? as I say though I do not want to push you or your lib where it does not wish to go. Perhaps making some issues would be Ok and you can clearly disagree/ignore etc., I have little ego so happy if that works for you..

### CODE REVIEW

**Comment by dirvine** [comment]
Seems travis may struggle with resources on the xor test. It does pass locally.

**Comment by TLmaK0** [comment]
Thanks @dirvine :). I have removed innovation numbers from this implementation, because for me innovation number it's the same as pair connection. So instead to search by innovation number I use neurons number connected (from, to). Then I didn't need a global sync variable to store next innovation number.

I will add some communication channel, like gitter.

For this PR, It will great if you can include travis to run rustfmt (good tool, I was thinking to include also rusty-clippy), and add some info about it in the readme for people who will try to help (I hope) with this.

**Comment by dirvine** [comment]
Really sorry about all the noise here, travis scripts are a bit strange at times. Please feel free to squash these commits.

**Comment by TLmaK0** [comment]
Wow!!, a lot of work here with travis :) Don't worry commits aren't a problem for me. Thanks for your help.

**Pull request merged**
