### PR TITLE
docs/examples Moved example to example folder

### PR DESCRIPTION
**Pull request by dirvine**
Small bug fix in example (mutability)
Reduced README in line with example

Please feel free to not accept this PR if it does not reflect your wishes. I think it may be an easier intro and simpler to test for users in this way, however that is an opinion. Anyhow, great to see this repo, a very exciting tech and crate indeed.

### CODE REVIEW

**Comment by TLmaK0** [comment]
Good! also would be great if we can maintain in the README how to use the lib.

**Comment by dirvine** [comment]
Yes I agree. I Am still trying to get a fuller understanding of the API. Things like setting the gene type & fitness measure as well as crossover/mutation ratios etc. If you have ideas it would be great and I will certainly put in some time there.  
Also travis / appveyor badges as well as link to docs.rs. can all be added. As I say I am happy to put in work here, but do not want to detract for your lib in any way. You have done some pretty amazing work here so I will "help out" where I can. 

Many thanks for the lib. I have spoken to a professor who is well versed in CTRNN, in fact one of his Phd doctorates now works with R. Beer. So we can also have some nice links for folk looking to dive deeper here.

**Comment by TLmaK0** [comment]
Awesome @dirvine!!

I will put travis badget ASAP.

Any help will be appreciated. There is also a lot of parameters that actually I'm guessing it.

My plans are try to use all CPUs (use GPUs in the future and scale to multiple machines), integrate with https://gym.openai.com/, integrate it with some kind of real-time charts library (for debugging purposes), include all CTRNN parameters in the NEAT algorithm, and make public some parameters that actually are fixed in the model.

I hope that at the end of this process, I will able to fully understand how CTRNN works and use it in real projects.

**Comment by dirvine** [comment]
Hopefully we can learn a bit together, it is a fascinating subject and seems NEAT is simpler than hyperneat. So a great start, hyperneat seems better at smaller sets but loses that improvement on largest problems. So NEAT seems like a great choice to start wit and CTRNN even more so. Anyhow if I can help I will, for sure.

**Pull request merged**
